<?php
require_once __DIR__ . '/includes/config.inc';
require_once __DIR__ . '/includes/mgc_robo.forms.inc';
require_once __DIR__ . '/includes/mgc_robo.admin.inc';
require_once __DIR__ . '/includes/mgc_robo.getters.inc';
require_once __DIR__ . '/includes/mgc_robo.helpers.inc';
require_once __DIR__ . '/includes/mgc_robo.pages.inc';
require_once __DIR__ . '/includes/mgc_robo.payment.inc';

function mgc_robo_menu() {
  $items['stats/teachers'] = array(
    'title'            => 'Статистика по учителям',
    'page callback'    => 'mgc_stats_teachers_page',
    'access callback'  => 'mgc_robo_access',
    'access arguments' => ['view robo'],
    'type'             => MENU_CALLBACK,
  );

  $items['stats/teachers/autocomplete'] = array(
    'page callback'    => 'mgc_get_user_search_autocomplete',
    'page arguments'   => array(3),
    'access callback'  => 'mgc_robo_access',
    'access arguments' => ['view robo'],
    'type'             => MENU_CALLBACK,
  );
  $items['robo/teachers']               = array(
    'title'            => 'Robokassa по учителям',
    'page callback'    => 'mgc_robo_teachers_page',
    'access callback'  => 'mgc_robo_access',
    'access arguments' => ['view robo'],
    'type'             => MENU_CALLBACK,
  );
  $items['set-tariff/%user']            = array(
    'page callback'    => 'mgc_robo_set_tariff_page',
    'page arguments'   => array(1),
    'type'             => MENU_CALLBACK,
    'access callback'  => 'mgc_robo_access',
    'access arguments' => ['view robo'],
  );

  $items['admin/config/robo'] = array(
    'title'            => 'Robokassa конфигурация',
    //'type'             => MENU_DEFAULT_LOCAL_TASK,
    'position'         => 'left',
    'weight'           => -100,
    'page callback'    => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file'             => 'system.admin.inc',
    'file path'        => drupal_get_path('module', 'system'),
  );

  $items['admin/config/robo/settings'] = array(
    'title'            => 'Настройки',
    'description'      => 'Настройки Robokassa: тарифы и прочее',
    'type'             => MENU_LOCAL_TASK,
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('mgc_robo_config_admin_form'),
    'access arguments' => array('access administration pages'),
    'weight'           => 10,
  );
  $items['robo/payment']               = array(
    'title'            => 'Оплата',
    'page callback'    => 'mgc_robo_payment_page',
    'access callback'  => 'mgc_robo_access',
    'access arguments' => ['view robo payment'],
    'type'             => MENU_CALLBACK,
  );

  return $items;
}

function mgc_robo_theme() {
  $path = drupal_get_path('module', 'mgc_robo') . '/templates';

  return array(
    'mgc_stats_teachers_page_theme' => array(
      'path'      => $path,
      'template'  => 'mgc-stats-teachers-page',
      'variables' => array(
        'image_path' => '',
      ),
    ),
    'mgc_robo_teachers_page'        => array(
      'path'      => $path,
      'template'  => 'mgc-robo-teachers-page',
      'variables' => array(
        'image_path' => '',
      ),
    ),
    'mgc_robo_payment_page'         => array(
      'path'      => $path,
      'template'  => 'mgc-robo-payment-page',
      'variables' => array(
        'image_path' => '',
      ),
    ),
    'mgc_robo_set_tariff_page'      => array(
      'path'      => $path,
      'template'  => 'mgc-robo-set-tariff-page',
      'variables' => array(
        'image_path' => '',
        'teacher'    => new stdClass(),
      ),
    ),

  );
}

function mgc_robo_access($op) {
  switch ($op) {

    case 'view robo':
      return user_access('administer');
      break;
    case 'view robo payment':
      return user_access('administer');
      break;
  }

  return FALSE;
}