<?php
require_once __DIR__ . '/includes/config.inc';
require_once __DIR__ . '/includes/mgc_robo.forms.inc';
require_once __DIR__ . '/includes/mgc_robo.getters.inc';
require_once __DIR__ . '/includes/mgc_robo.helpers.inc';
require_once __DIR__ . '/includes/mgc_robo.pages.inc';

function mgc_robo_menu() {
  $items['stats/teachers'] = array(
    'title'            => 'Статистика по учителям',
    'page callback'    => 'mgc_stats_teachers_page',
    'access callback'  => 'mgc_robo_access',
    'access arguments' => ['view robo'],
    'type'             => MENU_CALLBACK,
  );

  $items['stats/teachers/autocomplete'] = array(
    'page callback'    => 'mgc_get_user_search_autocomplete',
    'page arguments'   => array(3),
    'access callback'  => 'mgc_robo_access',
    'access arguments' => ['view robo'],
    'type'             => MENU_CALLBACK,
  );
  $items['robo/teachers']               = array(
    'title'            => 'Robokassa по учителям',
    'page callback'    => 'mgc_robo_teachers_page',
    'access callback'  => 'mgc_robo_access',
    'access arguments' => ['view robo'],
    'type'             => MENU_CALLBACK,
  );
  $items['set-tariff/%user']            = array(
    'page callback'     => 'mgc_robo_set_tariff_page',
    'page arguments'    => array(1),
    'type'              => MENU_CALLBACK,
    'access callback'   => TRUE,
    'delivery callback' => 'drupal_json_output',
  );

  return $items;
}

function mgc_robo_theme() {
  $path = drupal_get_path('module', 'mgc_robo') . '/templates';

  return array(
    'mgc_stats_teachers_page_theme' => array(
      'path'      => $path,
      'template'  => 'mgc-stats-teachers-page',
      'variables' => array(
        'image_path' => '',
      ),
    ),
    'mgc_robo_teachers_page'        => array(
      'path'      => $path,
      'template'  => 'mgc-robo-teachers-page',
      'variables' => array(
        'image_path' => '',
      ),
    ),
    'mgc_robo_set_tariff_page'        => array(
      'path'      => $path,
      'template'  => 'mgc-robo-teachers-page',
      'variables' => array(
        'image_path' => '',
      ),
    ),
  );
}

function mgc_robo_access($op) {
  switch ($op) {

    case 'view robo':
      return user_access('administer');
      break;
  }

  return FALSE;
}