<?php
define('MGC_ROBO_DEV', TRUE);

define('MGC_TEACHERS_CACHE_EXPIRE', 2 * 60 * 60);
define('MGC_ROBOKASSA_MRCH_LOGIN', 'rewrite');
define('MGC_ROBOKASSA_MRCH_PASS1', 'wd3X3s4jTgG1EynGafF7');
define('MGC_ROBOKASSA_MRCH_PASS2', 'esRsoA40223cijAyOUkt');
define('MGC_ROBOKASSA_MRCH_CURRENCY', 'RUB');
define('MGC_ROBOKASSA_MRCH_LANGUAGE', 'ru');
define('MGC_ROBOKASSA_MRCH_TEST', '1');
//define('MGC_FEEDBACK_MAIL', 'paul.nike@yandex.ru');
define('MGC_FEEDBACK_MAIL', '821olgazotova@gmail.com');
define('MGC_COURSE1_TARIFF_SHP_ITEM', '1');
define('MGC_COURSE2_TARIFF_SHP_ITEM', '2');
define('MGC_WEBINAR_TARIFF_SHP_ITEM', '3');
define('MGC_TRIAL_TIME_DAYS', '1');
/*PRUFFMELAB CONFIG*/
define('MGC_PRUFFMELAB_SERVER', variable_get('pruffmelab_server'));
define('MGC_PRUFFMELAB_USER_AGENT', variable_get('pruffmelab_user_agent'));
define('MGC_PRUFFMELAB_PARTNER_CODE', variable_get('pruffmelab_partner_code'));
define('MGC_PRUFFMELAB_PARTNER_KEY', variable_get('pruffmelab_partner_key'));
define('MGC_PRUFFMELAB_TARIFF_WITH_VIDEO', 1);
define('MGC_PRUFFMELAB_TARIFF_WITHOUT_VIDEO', 0);
define('MGC_PRUFFMELAB_LIMIT', variable_get('pruffmelab_limit'));

define('MGC_PRUFFMELAB_WEBINAR_SORTING_BY_ACTIVITY', 0);
define('MGC_PRUFFMELAB_WEBINAR_SORTING_BY_CREATED', 1);
define('MGC_PRUFFMELAB_WEBINAR_SORTING_BY_UPDATED', 2);



