<?php
define('MGC_TEACHERS_CACHE_EXPIRE', 2 * 60 * 60);
define('MGC_ROBOKASSA_MRCH_LOGIN', 'rewrite');
define('MGC_ROBOKASSA_MRCH_PASS1', 'wd3X3s4jTgG1EynGafF7');
define('MGC_ROBOKASSA_MRCH_PASS2', 'esRsoA40223cijAyOUkt');
define('MGC_ROBOKASSA_MRCH_CURRENCY', 'RUB');
define('MGC_ROBOKASSA_MRCH_LANGUAGE', 'ru');
define('MGC_ROBOKASSA_MRCH_TEST', '1');
//define('MGC_FEEDBACK_MAIL', 'paul.nike@yandex.ru');
define('MGC_FEEDBACK_MAIL', '821olgazotova@gmail.com');
define('MGC_COURSE1_TARIFF_SHP_ITEM', '1');
define('MGC_COURSE2_TARIFF_SHP_ITEM', '2');
define('MGC_WEBINAR_TARIFF_SHP_ITEM', '3');


